/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/navigation/AppSidebar.vue')['default']
    Badge: typeof import('./components/ui/Badge.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    ManagerPill: typeof import('./components/common/ManagerPill.vue')['default']
    PackageTable: typeof import('./components/packages/PackageTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusNotice: typeof import('./components/common/StatusNotice.vue')['default']
    TitleBar: typeof import('./components/common/TitleBar.vue')['default']
  }
}
