/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./components/ui/alert/AlertTitle.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    ButtonGroup: typeof import('./components/ui/button-group/ButtonGroup.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./components/ui/dialog/DialogOverlay.vue')['default']
    DialogPortal: typeof import('./components/ui/dialog/DialogPortal.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    GlobalLoadingBar: typeof import('./components/common/GlobalLoadingBar.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    PackagesDataTable: typeof import('./components/packages/PackagesDataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Table: typeof import('./components/ui/table/Table.vue')['default']
    TableBody: typeof import('./components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./components/ui/table/TableCell.vue')['default']
    TableHead: typeof import('./components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./components/ui/table/TableRow.vue')['default']
    TitleBar: typeof import('./components/common/TitleBar.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
    VersionSelectButton: typeof import('./components/packages/VersionSelectButton.vue')['default']
  }
}
