// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUninstallPackages(arg1, arg2) {
  return window['go']['main']['App']['BatchUninstallPackages'](arg1, arg2);
}

export function BatchUpdatePackages(arg1, arg2) {
  return window['go']['main']['App']['BatchUpdatePackages'](arg1, arg2);
}

export function GetCachedPackages() {
  return window['go']['main']['App']['GetCachedPackages']();
}

export function GetPackageInfo(arg1, arg2) {
  return window['go']['main']['App']['GetPackageInfo'](arg1, arg2);
}

export function InitManagerRegistry() {
  return window['go']['main']['App']['InitManagerRegistry']();
}

export function InstallPackage(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallPackage'](arg1, arg2, arg3);
}

export function ListEnabledManagers() {
  return window['go']['main']['App']['ListEnabledManagers']();
}

export function ListManagers() {
  return window['go']['main']['App']['ListManagers']();
}

export function ListPackageVersions(arg1, arg2) {
  return window['go']['main']['App']['ListPackageVersions'](arg1, arg2);
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function UninstallPackage(arg1, arg2) {
  return window['go']['main']['App']['UninstallPackage'](arg1, arg2);
}

export function UpdateCache() {
  return window['go']['main']['App']['UpdateCache']();
}

export function UpdatePackage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePackage'](arg1, arg2, arg3);
}
