// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manager} from '../models';

export function BatchUninstallPackages(arg1:Array<manager.Package>,arg2:manager.ActionOptions):Promise<manager.ActionResult>;

export function BatchUpdatePackages(arg1:Array<manager.Package>,arg2:manager.ActionOptions):Promise<manager.ActionResult>;

export function GetCachedPackages():Promise<Array<manager.Package>>;

export function GetPackageInfo(arg1:string,arg2:string):Promise<string>;

export function InitManagerRegistry():Promise<void>;

export function InstallPackage(arg1:string,arg2:string,arg3:manager.ActionOptions):Promise<manager.ActionResult>;

export function ListEnabledManagers():Promise<Array<manager.Info>>;

export function ListManagers():Promise<Array<manager.Info>>;

export function ListPackageVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function SearchPackages(arg1:string):Promise<Array<manager.Package>>;

export function UninstallPackage(arg1:string,arg2:string,arg3:manager.ActionOptions):Promise<manager.ActionResult>;

export function UpdateCache():Promise<void>;

export function UpdatePackage(arg1:string,arg2:string,arg3:manager.ActionOptions):Promise<manager.ActionResult>;
